export const HOME_ROUTE = '/'
export const MATH_ROUTE = '/math'


export const lab1_ROUTE = '/lab1'
export const lab2_ROUTE = '/lab2'
export const lab3_ROUTE = '/lab3'
export const lab4_ROUTE = '/lab4'
export const lab5_ROUTE = '/lab5'
export const lab6_ROUTE = '/lab6'
export const lab7_ROUTE = '/lab7'
export const lab8_ROUTE = '/lab8'
export const lab9_ROUTE = '/lab9'
export const lab10_ROUTE = '/lab10'
export const Sys_ROUTE = '/sys'